name: automerge

on:
  pull_request:
    types:
      - labeled
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
