on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        scala: [2.13.12]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          check-latest: true

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Compile and test
        run: sbt test
